package mx.infotec.dads.insight.pdes.model;

/**
 * Clase que lista los tipos de propiedades que se muestran en el reporte.
 * 
 * @author Daniel Cortes Pichardo
 *
 */
public enum Table {
    SEMANA_HORA_PLAN, SEMANA_HORA_ACTUAL, SEMANA_HORA_ACTUAL_PLAN, SEMANA_EV_PLAN, SEMANA_EV_ACTUAL, SEMANA_EV_ACTUAL_PLAN,

    A_LA_FECHA_HORA_PLAN, A_LA_FECHA_HORA_ACTUAL, A_LA_FECHA_HORA_ACTUAL_PLAN, A_LA_FECHA_EV_PLAN, A_LA_FECHA_EV_ACTUAL, A_LA_FECHA_EV_ACTUAL_PLAN,

    PROMEDIO_HORA_PLAN, PROMEDIO_HORA_ACTUAL, PROMEDIO_HORA_ACTUAL_PLAN, PROMEDIO_EV_PLAN, PROMEDIO_EV_ACTUAL, PROMEDIO_EV_ACTUAL_PLAN,

    TAREAS_HORA_PLAN, TAREAS_HORA_ACTUAL, TAREAS_HORA_ACTUAL_PLAN, TAREAS_EV_PLAN, TAREAS_EV_ACTUAL, TAREAS_EV_ACTUAL_PLAN,
}
